<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Starbender.FileClerk.Demo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Starbender.FileClerk.Demo.Domain\Starbender.FileClerk.Demo.Domain.csproj" />
    <ProjectReference Include="..\Starbender.FileClerk.Demo.TestBase\Starbender.FileClerk.Demo.TestBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
  </ItemGroup>

</Project>
