<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Starbender.FileClerk</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Domain" />
    <PackageReference Include="Volo.Abp.Identity.Domain" />
    <PackageReference Include="Volo.Abp.PermissionManagement.Domain" />
    <ProjectReference Include="..\Starbender.FileClerk.Domain.Shared\Starbender.FileClerk.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
