<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AbpVersion>10.6.0</AbpVersion>
    <MicrosoftNetVersion>10.0.11</MicrosoftNetVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="ConfigureAwait.Fody" Version="3.3.1" />
    <PackageVersion Include="Fody" Version="6.5.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="$(MicrosoftNetVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Proxies" Version="$(MicrosoftNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.FileProviders.Embedded" Version="$(MicrosoftNetVersion)" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="NSubstitute" Version="6.1.0" />
    <PackageVersion Include="NSubstitute.Analyzers.CSharp" Version="1.0.17" />
    <PackageVersion Include="Shouldly" Version="4.3.0" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Components.Server.Theming" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Components.Web.Theming" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Components.WebAssembly.Theming" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Components.WebAssembly.Theming.Bundling" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Mvc" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.Shared" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Authorization" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Autofac" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.BlobStoring" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Ddd.Application" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Ddd.Application.Contracts" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Ddd.Domain" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Ddd.Domain.Shared" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.EntityFrameworkCore" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Guids" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Http.Client" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.TestBase" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.Validation" Version="$(AbpVersion)" />
    <PackageVersion Include="Volo.Abp.VirtualFileSystem" Version="$(AbpVersion)" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.extensibility.execution" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
